version: '3.7'

services:
  db:
    image: postgres
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1952
      POSTGRES_DB: postsdb
    ports:
      - "5432:5432"

  migrate:
    image : migrate/migrate
    networks:
      - raim
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:1952@database:5432/postsdb?sslmode=disable", "up", "1"]
    links:
      - db

  scrapper-api:
    networks:
      - raim
    build: scrapper
    ports :
      - "8080:8080"
    depends_on:
      - db

  crawler:
    networks:
      - raim
    build: crawler
    depends_on:
      - db


networks:
  raim:
    external: true